---
title: "Final Project"
author: "Annie Glenning"
date: "2024-07-23"
output: pdf_document
---
```{r}
getwd() # finding my working directory 
```

```{r}
setwd("/Users/annieglenning/Documents/Dartmouth/SU24/QBS_103/Data") # set my working directory to where the data is stored
original_gene_data <- read.table("QBS103_GSE157103_genes.csv", header = TRUE, sep = ",") # reading in the data
series_data <- read.table("QBS103_GSE157103_series_matrix.csv", header = TRUE, sep = ",") # reading in the data
```

```{r}
# transposing the gene data 
original_gene_data <- as.data.frame(original_gene_data)
if (is.character(original_gene_data[1, 1])) {
  gene_data <- t(original_gene_data)
  colnames(gene_data) <- gene_data[1, ]
  gene_data <- gene_data[-1, ]
  gene_data <- as.data.frame(gene_data)
}
```

## Identify one gene, one continuous covariate, and two categorical covariates 

```{r}
AAGAB <- as.numeric(gene_data$AAGAB) # one gene 
AAGAB
```

```{r}
series_data$age # one continuous covariate 
series_data$sex # first categorical covariate
series_data$icu_status # second categorical covariate
```

## Generate the following three plots using ggplot2 

```{r}
library(tidyverse) 
```

```{r}
library(ggplot2)
```

### Histogram for my Gene selected

```{r}
ggplot(gene_data, aes(x = as.numeric(AAGAB))) +
  geom_histogram(binwidth = 2, fill = "cadetblue3", color = "cadetblue4") +
  labs( # labeling the title and axis
    title = "Histogram of AAGAB Gene Expression Levels", 
    x = "Expression Level", 
    y = "Frequency"
  ) +
  theme(
    plot.title = element_text(size = 20, face = "bold"), # title
    axis.title = element_text(size = 15, face = "bold"), # axis 
    panel.grid.major = element_line(color = "grey80"), # background 
    panel.grid.minor = element_line(color = "grey90")
    )
```

### Scatterplot 

```{r}
ggplot(series_data, aes(x = as.numeric(AAGAB), y = as.numeric(age), 
                        color = factor(icu_status))) + # seperarting the points by icu status 
  geom_point(size = 2.5, alpha = 0.8) + # size and transparency of the point
  labs( # labeling the title and axis 
    title = "Scatterplot of the AAGAB Expression Levels vs. Age", 
    x = "AAGAB Expression Levels", 
    y = "Age (yrs)",
    color = "ICU Status" # legend title
    ) + 
  theme(
    plot.title = element_text(size = 16, face = "bold"), 
    axis.title = element_text(size = 15, face = "bold"), 
    legend.title = element_text(size = 12, face = "bold"),  # editing the legend 
    legend.text = element_text(size = 10), 
    legend.background = element_rect(fill = "lightgray", color = NA), 
    legend.key = element_rect(fill = "white", color = "black"),
    panel.grid.major = element_line(color = "grey80"), # background 
    panel.grid.minor = element_line(color = "grey90")
    ) 
```
### Box Plot 

```{r}
ggplot(series_data,aes(x = icu_status, y = as.numeric(AAGAB), color = sex)) +
  geom_boxplot() +
  labs( # labeling the title and axis 
    title = "Box Plot of AAGAB Expression Levels by ICU Status and Sex",
    x = "ICU Status", 
    y = "AAGAB Expression Levels"
  ) +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"), # editing the legend 
    legend.text = element_text(size = 10),
    legend.background = element_rect(fill = "lightgray", color = NA), 
    legend.key = element_rect(fill = "white", color = "black"),
    panel.grid.major = element_line(color = "grey80"), # background 
    panel.grid.minor = element_line(color = "grey90")
  ) 
```

